language: elixir

elixir:
  - 1.5.1

addons:
  postgresql: '9.6.5'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
